### ISSUE TITLE
SeetaFace移植Android

### ISSUE THREAD

**Issue by Even201314** [imistyrain/SeetaFace4Android#1]
你好，我下载了Demo测试一下，目前Apk应该只是实现了人脸检测。我留意到SeetaFace人脸识别需要加载的文件有100M，所以我疑惑SeetaFace是否真的可以移植到实际Android项目中？

**Comment by imistyrain** [comment]
确实是只有检测和对齐的代码，手机由于性能的限制，做识别现阶段还不是特别合适，因此就放在了服务器端。
不过移植应该没什么难度，确实没用第三方的库，其实自己用第三方库的话速度可能会更快些

**Comment by anguoyang** [comment]
能否移植一下识别部分？

**Comment by imistyrain** [comment]
识别部分没有用到第三方库，移植应该没什么难度，就是模型太大了，在手机上不合适

**Comment by imistyrain** [comment]
识别部分没有用到第三方库，移植应该没什么难度，就是模型太大了，在手机上不合适

**Comment by AustinCanlin** [comment]
你好，apk demo 能提供源码么

**Comment by imistyrain** [comment]
识别部分移植已经完成

**Comment by anguoyang** [comment]
@imistyrain 貌似还没看到：）

**Comment by imistyrain** [comment]
由于涉及代码转让，暂时还不能发布AS源工程，见谅

**Comment by xh2009cn** [comment]
您好，请问能否不用libopencv_java3.so，直接用jni调用？libopencv_java3.so太大了，apk一下增加10M

**Comment by imistyrain** [comment]
seetaface本身不依赖opencv，可以去掉，不过要改些代码，麻烦些

**Comment by xh2009cn** [comment]
请问SeetaFaceEngine-windows里面的代码可以直接编译成so吗？我在windows下用ndk编译了一下，好像不行，报use of undeclared identifier '__builtin_ia32**'错误。

**Comment by imistyrain** [comment]
可以直接编译，可能是你使用的SDK版本太低吧。

**Comment by xiejinde** [comment]
你好，我安装了工程里面的SeetaFace4Android.apk，并安装了opencv3.0，应用运行后调用了前置摄像头，但是没有人脸检测结果？是不是我使用不当？

**Comment by imistyrain** [comment]
可能是opencv没有正确调用吧
